### ISSUE TITLE
syntax error in less/type.less

### ISSUE THREAD

**Issue by kfinke** [typo3-themes/theme_bootstrap#16]
Hi,

don't know why but the compiler gives me this syntax-error when I save the import.less in my theme:

ParseError: Syntax Error on line 211 in C:\typo3-themes-box-2\project\typo3conf\ext\theme_bootstrap\Resources\Public\Contrib\Bootstrap\less\type.less:211:4
```
dd {
    &:extend(.clearfix all); // Clear the floated `dt` if an empty `dd` is present
}
```

**Comment by kaystrobach** [comment]
* which version of dyncss are you using?
* have you changed one of the files or one of the surrounding files?

**Comment by kfinke** [comment]
dyncss 0.7.3
no, I did not change a file in theme_bootstrap.

**Comment by kaystrobach** [comment]
lets talk on slack ...

**Comment by kaystrobach** [comment]
solved after discussion
