### ISSUE TITLE
Use the bootstrap-classes for sysext "form"

### ISSUE THREAD

**Issue by kfinke** [typo3-themes/theme_bootstrap#17]
The bootstrap_package-extension uses the bootstrap-classes for forms, e.g. "form-group" or "form-control" by default Wouldn't it be good to take them also for theme_bootstrap?
\ext\bootstrap_package\Configuration\ContentElements\Base.ts (line 820 ff.)

I am not sure, whether the same would be useful or is already implemented for other content-elements.

**Comment by kaystrobach** [comment]
@kfinke just extract the TS + Fluid from benjamin extensions and start a merge request ... this is definitly a good idea for theme_bootstrap
