### ISSUE TITLE
let grids show headers

### ISSUE THREAD

**Issue by kaystrobach** [typo3-themes/theme_bootstrap#20]
@Bunnyfield @tdeuling what do you think about letting themes_gridelements show headers of gridelements by default? IMHO atleast the multicolumn elements should be able to do that ... or the TCA fields should be hidden

```
tt_content.gridelements_pi1.10=<lib.stdheader
```

**Comment by Bunnyfield** [comment]
Well, usually there is no header in the frontend for a structure or container element. BUT you will need the headers in the backend for management of the container. So editors will know what this particular container is all about.

So IMHO we should keep it as is and if there are people who want to have a frontend output for the container headers, they can still apply some lib.stdheader stuff at the appropriate places.

**Comment by kaystrobach** [comment]
ok, maybe we should rename the field then ...

**Comment by kaystrobach** [comment]
moved to a blueprint
