### ISSUE TITLE
add canonical -> needs some refinement

### ISSUE THREAD

**Issue by kaystrobach** [typo3-themes/theme_bootstrap#26]
```
page.headerData {
700 = TEXT
700 {
    stdWrap.typolink.parameter.data = TSFE:id
    stdWrap.typolink.forceAbsoluteUrl = 1
    stdWrap.typolink.returnLast = url
    htmlSpecialChars = 1
    wrap = <link href="|" rel="canonical" />
  }
}
```

**Comment by kaystrobach** [comment]
maybe better integrate own field, automation may break other stuff here ...

**Comment by t-zimmermann** [comment]
Why not use tq_seo ?
See discussion on:
http://typo3blogger.de/seo-canonical-urls-fur-eindeutige-seitenmarkierung/

**Comment by tdeuling** [comment]
First of all, I heard about that the development of tq_Seo has been stopped. meta_seo is a similar new extension. But our goal is, to use less extensions as possible and try to solve things with simple TypoScript or TYPO3 features.
If you need further features which we're currently not providing, you and everyone is free to use additional extensions.
But thanks for your suggestion :)

**Comment by kaystrobach** [comment]
@tdeuling can you take a look please?

**Comment by kaystrobach** [comment]
use yoast seo
