### ISSUE TITLE
Wrong code if themes.configuration.menu.main.doNotLinkFirstLevelPagesWithSubPages is true

### ISSUE THREAD

**Issue by responseinformationsdesign** [typo3-themes/theme_bootstrap#30]
There are some more changes necessary for the typoscript code (not only doNotLinkIt = 1)

_should be empty_
`before >`

_caret should do the dropwodn-toggle as menu item is linked_
`after = <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>`

**Comment by kaystrobach** [comment]
Would be awesome if you would open a PR AS well ;)

**Comment by kaystrobach** [comment]
any news non that?

**Comment by responseinformationsdesign** [comment]
It looks like Bootstrap 3 has dropped support for mulitlevel dropdowns (http://www.monolinea.com/responsive-multilevel-menu-with-bootstrap-3/). Should this be supported for "Bootstrap Theme" (which uses Bootstrap 3) anyway?
