### ISSUE TITLE
Bootstrap menu crashing when setting checking Do not link first level pages to "0"

### ISSUE THREAD

**Issue by lisandi** [typo3-themes/theme_bootstrap#33]
To make the first level of bootstrap linking to a certain page you need to set 
themes.configuration.menu.main.doNotLinkFirstLevelPagesWithSubPages = 0
default is
themes.configuration.menu.main.doNotLinkFirstLevelPagesWithSubPages = 1

When set to = 0 the menu gets displayed in two rows and is no more showing the second level.

It is existing in all Templates using theme_bootstrap as a base

**Comment by kaystrobach** [comment]
hey @lisandi please propose a RFC / PR to fix that - thank you.
