### ISSUE TITLE
[FEATURE] If Definitions in /Configuration/TypoScript/Library/themes.bootstrap.less.constantsts have highest priority...

### ISSUE THREAD

**Issue by t-zimmermann** [typo3-themes/theme_bootstrap#40]
In Case of using Bootstrap:
This file /Configuration/TypoScript/Library/themes.bootstrap.less.constantsts should have "highest priority" in assignment to Dyncss. So Every value assigned to Dyncss in /Configuration/TypoScript/Library/plugin.dyncss.bootstrap3.setupts should be "outsourced" to /Configuration/TypoScript/Library/themes.bootstrap.less.constantsts (assignments in the first file should be moved to the later file).

**Comment by kaystrobach** [comment]
could you please provide a PR for that? - thank you
