### ISSUE TITLE
[FEATURE] Add the possibility to Style Pages depanding on: Page:alias/uid; Page-level, Sys-Language, BackendLayout, FrontendLayout

### ISSUE THREAD

**Issue by t-zimmermann** [typo3-themes/theme_bootstrap#41]
This could be done by a lib in: /configuration/TypoScript/Library/lib.page.setupts
like this:
# adds class-names for page-id, pagelevel, language-id, backend-layout-id and layout-id, so you could style the language per selected language or pagelevel....

lib.page.class = COA
lib.page.class {
    // Page alias or id as fallback
    10 = TEXT
    10 {
        data = field:alias // field:uid
        noTrimWrap = |page-||
    }
    // Current level of the page within the tree structure
    20 = TEXT
    20 {
        data = level:1
        noTrimWrap = | pagelevel-||
    }
    // id of language the Frontend starts up as default (at the moment, this is NOT bound to Menu in Themes! Should be done!)
    30 = TEXT
    30 {
        data = TSFE:sys_language_uid
        noTrimWrap = | language-||
    }
    // Backend layout (page properties -> Appearance)
    40 = TEXT
    40 {
        data = levelfield:-1, backend_layout_next_level, slide
        override.data = field:backend_layout
        ifEmpty = default
        noTrimWrap = | backendlayout-||
    }
    // Frontend Layout
    50 = TEXT
    50 {
        data = field:layout
        noTrimWrap = | layout-||
    }
}

In your layouts / templates you could bind this like this:
.......

```
        <section id="p{data.uid}" class="{f:cObject(typoscriptObjectPath:'lib.page.class')}">
            <f:render partial="Mypartial" section="Default" arguments="{_all}" />
        </section>
```

**Comment by Shade634** [comment]
I am kinda missing the point in this? 
For styling specific pages differently one class on the bodytag should be enough?

**Comment by kaystrobach** [comment]
maybe he wants something like `page-<uid> and page-<uid>-<languid>`?

**Comment by tdeuling** [comment]
How about that: 
https://github.com/typo3-themes/theme_bootstrap4/blob/master/Configuration/TypoScript/Library/Page/page.setupts

**Comment by tdeuling** [comment]
`page-layout-1 page-alias-aliasname page-level-3 page-layout-backend-menucontent language-en`

**Comment by tdeuling** [comment]
alternatively: `page-backendlayout-menucontent`

**Comment by Shade634** [comment]
page-alias-aliasname be carefull with special chars ;)

**Comment by Lobster1956** [comment]
in my layouts i'm using such bodyclasses very often... my basic set is:
id="pageUID-XX" class="pagePID-XX pageRID-XX pageRID-XX pageLEVEL-XX pageLAYOUT-XX pageBELAYOUT-XX  pageLANGUAGE-XX"
- PID is the parent ID
- RID are the rootline IDs

with such classes i'm able to styling every page inividual if i wish that...
In some cases i also have morning midday afternoon evening night usergroups and userID inside this (but this is not recomended because of caching several versions)

**Comment by kaystrobach** [comment]
mhmm ok, question is if we can do an "easy and cheap one" as default and have another "extended" one via constants as option? IMHO having tons of classes here makes rendering slow - esp. on some mobile browsers.

**Comment by Shade634** [comment]
Agreed, there is something like having to much classes.

**Comment by Lobster1956** [comment]
i myself don't need such classes as default (UID PID RID are the only i use in every template because it helps a lot for quick restyling whole pagetrees), it is no problem to add this classes in the own template... i only want to show that such classes could be very usefull...

**Comment by kaystrobach** [comment]
@t-zimmermann @tdeuling do you agree?

**Comment by kaystrobach** [comment]
feedback?
