### ISSUE TITLE
Problems with News

### ISSUE THREAD

**Issue by Nostrabramus** [typo3-themes/theme_bootstrap#50]
Hello, 
I report here an issue already posted on slack
I'm having problem with News extension. I'm using TYPO3 7.6.12, themes 7.0.3,  theme_bootstrap 7.0.1 and news 5.3.1.

I create my own skin (cloning theme_bootstrap_slate) and everything goes fine until try to use the News plugin on a page: when I try to view the page I'm getting the following exception: 

`Uncaught TYPO3 Exception
#1289386765: Could not analyse class: "Tx_News_ViewHelpers_Widget_PaginateViewHelper" maybe not loaded or no autoloader? Class Tx_News_ViewHelpers_Widget_PaginateViewHelper does not exist (More information)`

Whatever kind of news plugin mode I use I get an exception about news viewhelpers.

I already tried to let news work under another theme_boostrap template (theme_bootstrap and theme_boostrap_slate) but the problem still persist. When I use news without using theme it works nice.

I see that while template analyzier shows that ts templates file of theme_boostrap for news is loaded, I cannot see the variables populated in typoscript object browser. I'm talking about this code: **theme_bootstrap/Resources/Private/Extensions/News/Typoscript/setup.txt**

This happens while I have not loaded any additional typoscript.

Any idea on what can goes wrong?

**Comment by kaystrobach** [comment]
@Nostrabramus are you only using the plain bootstrap skin or another one?

In News 5.x the compat layer for old viewHelpers had been removed, IMHO the master of the themes extensions contain the fix already.
Maybe you also need to clear the class cache of your TYPO3 Installation:

http://insight.helhum.io/post/130812561790/changes-in-class-loading-in-typo3-7lts

```
typo3/cli_dispatch.phpsh extbase extension:dumpclassloadinginformation
```

**Comment by kaystrobach** [comment]
What i forgot, if you have a custom theme, you might need to change the news viewHelper usage in that theme as well

/cc @tdeuling

**Comment by kaystrobach** [comment]
@Nostrabramus please check what content your theme_bootstrap contains in the following file:

https://github.com/typo3-themes/theme_bootstrap/commit/89033ef4c0b34041f7531ae0cd45e0950ebcbbac

If that it not similar to the one in master, we may need to do a release of theme_bootstrap earlier, as this was changed in news

**Comment by Nostrabramus** [comment]
@kaystrobach 
first of all thanks

Yes I'm using a custom theme, but I'm testing news  extension also with bootstrap_theme_slate and I have the same error

I cleared the cache in all the way I know, including manual delete of typo3temp folder

I'm using the master of theme_bootstrap (7.0.1) 

I checked the file **theme_bootstrap/Resources/Private/Extensions/News/Partials/List/Item.html** and it's identical to the one you showed me (https://github.com/typo3-themes/theme_bootstrap/commit/89033ef4c0b34041f7531ae0cd45e0950ebcbbac)

**Comment by Nostrabramus** [comment]
@kaystrobach it was not a theme_bootstrap issue, I had copied a news fluid template in my custom theme extension without modifying properly the namespace inclusion of the viewhelper, that in news is made without namespaces.
Using the template form theme_bootstrap and it works.
Thank you for showing me the right path to the solution 👍
