### ISSUE TITLE
mention backend layouts in Templates/Theme/Error.html

### ISSUE THREAD

**Issue by sunfish** [typo3-themes/theme_bootstrap#53]
If you are not familiar with the theme package, it would be a help if the error text is changed, so missing backend layout is mentioned. 

Current text:
Currently you have not selected a _**template**_ for this page or extended a parent page. Please select one in the page properties.

Text suggestion:
Currently you did not select a _**backend layout**_ for this page or extended a parent page. Please select one in the page properties.

By the way, I think the typo3 themes are a great thing!!! Thank you for your work.

**Comment by tdeuling** [comment]
Hi, thanks for your ticket.
There was already an improved error message in EXT:themes - I've used this.
