### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by responseinformationsdesign** [typo3-themes/theme_bootstrap#54]
Where should extension specific PageTS ideally be stored?

For "htmlArea RTE" and "theme_bootstrap" f. e. two different folders were used:

- theme_bootstrap/Configuration/PageTS/Library/rte.pagets
- theme_bootstrap/Resources/Private/Extensions/Rtehtmlarea/PageTS/tsconfig.txt

**Comment by kaystrobach** [comment]
@responseinformationsdesign these 2 configs have 2 scopes ... FE and BE. Closing for now, please come back if the problem still exists.
