### ISSUE TITLE
 TypoScript object path "lib.page.title" does not exist

### ISSUE THREAD

**Issue by kfinke** [typo3-themes/theme_bootstrap#7]
lib.page.title is used in Main.html, but nowhere defined. 

TypoScript object path "lib.page.title" does not exist

**Comment by tdeuling** [comment]
These elements are provided by the themes_gridelements extension, because of they're useful for all possible theme-packages.
See: http://docs.typo3-themes.org/themes-gridelements/chapter/Configuration|TypoScript|Setup|Lib|Index/
