### ISSUE TITLE
: fehlt in 2 Definitionen von Konstanten...

### ISSUE THREAD

**Issue by web2date** [typo3-themes/theme_bootstrap#9]
``# General
#############################################

# cat=footer,basic//; type=string; label= Footer: address
themes.configuration.footer.address = TYPO3-Themes: Inspiring people to share

# cat=footer,basic//; type=string; label= Footer: E-Mail address
themes.configuration.footer.email = info@typo3-themes.org``

Für einheitliche Darstellung...alle anderen sind Doppelpunkt separiert...

**Comment by kaystrobach** [comment]
fixed locally, push not possible
